import bcrypt from 'bcryptjs';

/**
 * Password hashing.
 *
 * bcrypt with a per-password salt, generated by the library. Plaintext
 * passwords are never stored, logged, or returned from any API.
 */

// 12 rounds: comfortably above the commonly cited floor of 10, while staying
// fast enough not to become a denial-of-service vector on a serverless
// function, where each sign-in pays the full cost.
const BCRYPT_ROUNDS = 12;

export const MIN_PASSWORD_LENGTH = 12;

export async function hashPassword(plain: string): Promise<string> {
  return bcrypt.hash(plain, BCRYPT_ROUNDS);
}

/**
 * Always runs a real bcrypt comparison, even when the account has no password
 * (OAuth-only) or does not exist. Returning early in those cases would make
 * "no such user" measurably faster than "wrong password", letting an attacker
 * enumerate which email addresses are registered by timing alone.
 */
const DUMMY_HASH = '$2a$12$C6UzMDM.H6dfI/f/IKcEeO1S7bYzE5FBZ0T4uNP1nAqUYLZ.5NoAy';

export async function verifyPassword(
  plain: string,
  storedHash: string | null | undefined
): Promise<boolean> {
  const hash = storedHash ?? DUMMY_HASH;
  const ok = await bcrypt.compare(plain, hash);
  return storedHash ? ok : false;
}

/**
 * Deliberately conservative: length is the property that most affects how hard
 * a hash is to crack, so it is enforced over composition rules, which mainly
 * push people towards predictable substitutions.
 */
export function validatePassword(plain: string): { ok: boolean; error?: string } {
  if (typeof plain !== 'string' || plain.length < MIN_PASSWORD_LENGTH) {
    return { ok: false, error: `Password must be at least ${MIN_PASSWORD_LENGTH} characters.` };
  }
  if (plain.length > 200) {
    // bcrypt only considers the first 72 bytes; a very long input is also a
    // cheap way to burn CPU on every attempt.
    return { ok: false, error: 'Password must be at most 200 characters.' };
  }
  return { ok: true };
}

export function normalizeEmail(email: string): string {
  return email.trim().toLowerCase();
}

export function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) && email.length <= 254;
}
